[always.packages]
include = [ "@xfce-desktop-environment", "@xfce-apps", "@xfce-extra-plugins", "@xfce-media", "@xfce-office", "wget", "system-config-printer",]
exclude = [ "autofs", "acpid", "gimp-help", "desktop-backgrounds-basic", "xfce4-sensors-plugin", "xfce4-eyes-plugin",]

[format.installer-live]
filename = "installer.iso"

[format.vhd]
filename = "disk.vhd"

[format.installer-live.packages]
exclude = [ "@dial-up", "@input-methods", "@standard", "gfs2-utils", "reiserfs-utils", "fcoe-utils", "device-mapper-multipath",]
include = [ "kernel", "kernel-modules", "kernel-modules-extra", "anaconda", "anaconda-install-env-deps", "anaconda-live", "@anaconda-tools", "aajohan-comfortaa-fonts", "dracut-live", "glibc-all-langpacks", "livesys-scripts",]

[format.vhd.packages]
include = [ "@core", "chrony", "langpacks-en", "net-tools", "ntfsprogs", "libxcrypt-compat", "initscripts", "glibc-all-langpacks",]
exclude = [ "dracut-config-rescue", "geolite2-city", "geolite2-country", "zram-generator-defaults",]

[format.installer-live.files."/etc/sysconfig/desktop"]
content = "PREFERRED=/usr/bin/startxfce4\nDISPLAYMANAGER=/usr/sbin/lightdm"

[format.installer-live.files."/etc/sysconfig/livesys"]
content = "'livesys_session=\"xfce\"'"

[format.installer-live.systemd.services]
enable = [ "livesys.service", "livesys-late.service", "tmp.mount",]

[format.vhd.systemd.services]
enable = [ "sshd.service",]
disable = [ "proc-sys-fs-binfmt_misc.mount", "loadmodules.service",]
