[always.packages]
include = [ "@workstation-product-environment",]

[format.installer-live]
filename = "installer.iso"

[format.vhd]
filename = "disk.vhd"
filesize = 2000000000

[format.qcow2]
filename = "disk.qcow2"
filesize = 5000000000

[format.vmdk]
filename = "disk.vmdk"
filesize = 2000000000

[format.ova]
filename = "disk.ova"
filesize = 2000000000

[format.installer-live.packages]
exclude = [ "@dial-up", "@input-methods", "@standard", "gfs2-utils", "reiserfs-utils", "fcoe-utils", "device-mapper-multipath",]
include = [ "kernel", "kernel-modules", "kernel-modules-extra", "anaconda", "anaconda-install-env-deps", "anaconda-live", "@anaconda-tools", "aajohan-comfortaa-fonts", "dracut-live", "glibc-all-langpacks", "livesys-scripts",]

[format.vhd.packages]
include = [ "@core", "chrony", "langpacks-en", "net-tools", "ntfsprogs", "libxcrypt-compat", "initscripts", "glibc-all-langpacks",]
exclude = [ "dracut-config-rescue", "geolite2-city", "geolite2-country", "zram-generator-defaults",]

[format.qcow2.packages]
include = [ "chrony", "langpacks-en", "qemu-guest-agent",]
exclude = [ "dracut-config-rescue", "firewalld", "geolite2-city", "geolite2-country", "plymouth",]

[format.vmdk.packages]
include = [ "chrony", "systemd-udev", "langpacks-en", "open-vm-tools",]
exclude = [ "dracut-config-rescue", "etables", "firewalld", "geolite2-city", "geolite2-country", "gobject-introspection", "plymouth", "zram-generator-defaults", "grubby-deprecated", "extlinux-bootloader",]

[format.ova.packages]
include = [ "chrony", "systemd-udev", "langpacks-en", "open-vm-tools",]
exclude = [ "dracut-config-rescue", "etables", "firewalld", "geolite2-city", "geolite2-country", "gobject-introspection", "plymouth", "zram-generator-defaults", "grubby-deprecated", "extlinux-bootloader",]

[format.installer-live.files."/etc/sysconfig/livesys"]
content = "'livesys_session=\"gnome\"'"

[format.installer-live.systemd.services]
enable = [ "livesys.service", "livesys-late.service", "tmp.mount",]

[format.vhd.systemd.services]
enable = [ "sshd.service",]
disable = [ "proc-sys-fs-binfmt_misc.mount", "loadmodules.service",]

[format.qcow2.systemd.services]
enable = [ "cloud-init.service", "cloud-config.service", "cloud-final.service", "cloud-init-local.service",]
