[always.packages]
include = [ "@kde-product-environment", "@firefox", "@kde-apps", "@kde-media", "@kde-pim", "@libreoffice", "libreoffice-draw", "libreoffice-math", "fedora-release-kde", "kde-l10n", "fuse", "mediawriter",]
exclude = [ "@admin-tools", "tracker-miners", "tracker", "ktorrent", "digikam", "kipi-plugins", "krusader", "k3b",]

[format.vhd]
filesize = 2147483648

[format.qcow2]
filesize = 5368709120

[format.vmdk]
filesize = 2147483648

[format.ova]
filesize = 2147483648

[outputs.fedora-kde-x86_64-live]
filename = "fedora-kde-x86_64.iso"
format = "live-installer"
architecture = "x86_64"

[outputs.fedora-kde-aarch64-live]
filename = "fedora-kde-aarch64.iso"
format = "live-installer"
architecture = "aarch64"

[outputs.fedora-kde-aarch64-rpi-live]
filename = "fedora-kde-aarch64.iso"
format = "live-installer"
architecture = "aarch64"
platform = "rpi"

[outputs.fedora-kde-ppc64le-live]
filename = "fedora-kde-aarch64.iso"
format = "live-installer"
architecture = "aarch64"

[format.installer-live.packages]
exclude = [ "@dial-up", "@input-methods", "@standard", "gfs2-utils", "reiserfs-utils", "fcoe-utils", "device-mapper-multipath",]
include = [ "kernel", "kernel-modules", "kernel-modules-extra", "anaconda", "anaconda-install-env-deps", "anaconda-live", "@anaconda-tools", "aajohan-comfortaa-fonts", "dracut-live", "glibc-all-langpacks", "livesys-scripts",]

[format.vhd.packages]
include = [ "@core", "chrony", "langpacks-en", "net-tools", "ntfsprogs", "libxcrypt-compat", "initscripts", "glibc-all-langpacks",]
exclude = [ "dracut-config-rescue", "geolite2-city", "geolite2-country", "zram-generator-defaults",]

[format.qcow2.packages]
include = [ "chrony", "langpacks-en", "qemu-guest-agent",]
exclude = [ "dracut-config-rescue", "firewalld", "geolite2-city", "geolite2-country", "plymouth",]

[format.vmdk.packages]
include = [ "chrony", "systemd-udev", "langpacks-en", "open-vm-tools",]
exclude = [ "dracut-config-rescue", "etables", "firewalld", "geolite2-city", "geolite2-country", "gobject-introspection", "plymouth", "zram-generator-defaults", "grubby-deprecated", "extlinux-bootloader",]

[format.ova.packages]
include = [ "chrony", "systemd-udev", "langpacks-en", "open-vm-tools",]
exclude = [ "dracut-config-rescue", "etables", "firewalld", "geolite2-city", "geolite2-country", "gobject-introspection", "plymouth", "zram-generator-defaults", "grubby-deprecated", "extlinux-bootloader",]

[format.installer-live.files."/root/.gtkrc-2.0"]
content = "include /usr/share/themes/Adwaita/gtk-2.0/gtkrc\ninclude /etc/gtk-2.0/gtkrc\ngtk-theme-name=Adwaita"

[format.installer-live.files."/root/.config/gtk-3.0"]
content = "[Settings]\ngtk-theme-name = Adwaita"

[format.installer-live.files."/etc/sysconfig/livesys"]
content = "'livesys_session=\"kde\"'"

[format.installer-live.systemd.services]
enable = [ "livesys.service", "livesys-late.service", "tmp.mount",]

[format.vhd.systemd.services]
enable = [ "sshd.service",]
disable = [ "proc-sys-fs-binfmt_misc.mount", "loadmodules.service",]

[format.qcow2.systemd.services]
enable = [ "cloud-init.service", "cloud-config.service", "cloud-final.service", "cloud-init-local.service",]
